#pragma once

#include "stdafx.h"
#include "StreamWatchDlg.h"
#include "afxwin.h"

//#include "global.h"

// CStream_Watch_Tab4 dialog

class CStream_Watch_Tab4 : public CDialog
{
	DECLARE_DYNAMIC(CStream_Watch_Tab4)

public:
	CStream_Watch_Tab4(CWnd* pParent, CStream_WatchDlg* parent_Dlg);   // standard constructor
	virtual ~CStream_Watch_Tab4();

// Dialog Data
	enum { IDD = IDD_STREAM_WATCH_TAB4 };
protected:
	CStream_WatchDlg* m_parent_dlg;
	CToolTipCtrl* m_pToolTip;
public:
	CStatusMembers StatusTab;
//virtual BOOL PreTranslateMessage(MSG* pMsg);
	BOOL OnInitDialog();

protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support
		virtual BOOL PreTranslateMessage(MSG* pMsg);
	DECLARE_MESSAGE_MAP()
public:
	//CTabGeneral General_Tab4;

	afx_msg void OnBnClickedButtonStatusStart1();
	afx_msg void OnBnClickedButtonStatusStart2();
	afx_msg void OnBnClickedButtonStatusStart3();
	afx_msg void OnBnClickedButtonStatusStart4();
	afx_msg void OnBnClickedButtonStatusStart5();
	afx_msg void OnBnClickedButtonStatusStart6();
	afx_msg void OnBnClickedButtonStatusStart7();
	afx_msg void OnBnClickedButtonStatusStart8();
	afx_msg void OnBnClickedButtonStatusStart9();
	afx_msg void OnBnClickedButtonStatusStart10();
	afx_msg void OnBnClickedButtonStatusStart11();
	afx_msg void OnBnClickedButtonStatusStart12();
	afx_msg void OnBnClickedButtonStatusStart13();
	afx_msg void OnBnClickedButtonStatusStart14();
	afx_msg void OnBnClickedButtonStatusStart15();
	afx_msg void OnBnClickedButtonStatusStart16();
	afx_msg void OnBnClickedButtonStatusStart17();
	afx_msg void OnBnClickedButtonStatusStart18();
	afx_msg void OnBnClickedButtonStatusStart19();
	afx_msg void OnBnClickedButtonStatusStart20();
	afx_msg void OnBnClickedButtonStatusStart21();
	afx_msg void OnBnClickedButtonStatusStart22();
	afx_msg void OnBnClickedButtonStatusStart23();
	afx_msg void OnBnClickedButtonStatusStart24();
	afx_msg void OnBnClickedButtonStatusStart25();
	afx_msg void OnBnClickedButtonStatusStart26();
	afx_msg void OnBnClickedButtonStatusStart27();
	afx_msg void OnBnClickedButtonStatusStart28();
	afx_msg void OnBnClickedButtonStatusStart29();
	afx_msg void OnBnClickedButtonStatusStart30();
	afx_msg void OnBnClickedButtonStatusStart31();
	afx_msg void OnBnClickedButtonStatusStart32();
	afx_msg void OnBnClickedButtonStatusStart33();
	afx_msg void OnBnClickedButtonStatusStart34();
	afx_msg void OnBnClickedButtonStatusStart35();
	afx_msg void OnBnClickedButtonStatusStart36();
	afx_msg void OnBnClickedButtonStatusStart37();
	afx_msg void OnBnClickedButtonStatusStart38();
	afx_msg void OnBnClickedButtonStatusStart39();
	afx_msg void OnBnClickedButtonStatusStart40();
	afx_msg void OnBnClickedButtonStatusStart41();
	afx_msg void OnBnClickedButtonStatusStart42();
	afx_msg void OnBnClickedButtonStatusStart43();
	afx_msg void OnBnClickedButtonStatusStart44();
	afx_msg void OnBnClickedButtonStatusStart45();
	afx_msg void OnBnClickedButtonStatusStart46();
	afx_msg void OnBnClickedButtonStatusStart47();
	afx_msg void OnBnClickedButtonStatusStart48();
	afx_msg void OnBnClickedButtonStatusStop1();
	afx_msg void OnBnClickedButtonStatusStop2();
	afx_msg void OnBnClickedButtonStatusStop3();
	afx_msg void OnBnClickedButtonStatusStop4();
	afx_msg void OnBnClickedButtonStatusStop5();
	afx_msg void OnBnClickedButtonStatusStop6();
	afx_msg void OnBnClickedButtonStatusStop7();
	afx_msg void OnBnClickedButtonStatusStop8();
	afx_msg void OnBnClickedButtonStatusStop9();
	afx_msg void OnBnClickedButtonStatusStop10();
	afx_msg void OnBnClickedButtonStatusStop11();
	afx_msg void OnBnClickedButtonStatusStop12();
	afx_msg void OnBnClickedButtonStatusStop13();
	afx_msg void OnBnClickedButtonStatusStop14();
	afx_msg void OnBnClickedButtonStatusStop15();
	afx_msg void OnBnClickedButtonStatusStop16();
	afx_msg void OnBnClickedButtonStatusStop17();
	afx_msg void OnBnClickedButtonStatusStop18();
	afx_msg void OnBnClickedButtonStatusStop19();
	afx_msg void OnBnClickedButtonStatusStop20();
	afx_msg void OnBnClickedButtonStatusStop21();
	afx_msg void OnBnClickedButtonStatusStop22();
	afx_msg void OnBnClickedButtonStatusStop23();
	afx_msg void OnBnClickedButtonStatusStop24();
	afx_msg void OnBnClickedButtonStatusStop25();
	afx_msg void OnBnClickedButtonStatusStop26();
	afx_msg void OnBnClickedButtonStatusStop27();
	afx_msg void OnBnClickedButtonStatusStop28();
	afx_msg void OnBnClickedButtonStatusStop29();
	afx_msg void OnBnClickedButtonStatusStop30();
	afx_msg void OnBnClickedButtonStatusStop31();
	afx_msg void OnBnClickedButtonStatusStop32();
	afx_msg void OnBnClickedButtonStatusStop33();
	afx_msg void OnBnClickedButtonStatusStop34();
	afx_msg void OnBnClickedButtonStatusStop35();
	afx_msg void OnBnClickedButtonStatusStop36();
	afx_msg void OnBnClickedButtonStatusStop37();
	afx_msg void OnBnClickedButtonStatusStop38();
	afx_msg void OnBnClickedButtonStatusStop39();
	afx_msg void OnBnClickedButtonStatusStop40();
	afx_msg void OnBnClickedButtonStatusStop41();
	afx_msg void OnBnClickedButtonStatusStop42();
	afx_msg void OnBnClickedButtonStatusStop43();
	afx_msg void OnBnClickedButtonStatusStop44();
	afx_msg void OnBnClickedButtonStatusStop45();
	afx_msg void OnBnClickedButtonStatusStop46();
	afx_msg void OnBnClickedButtonStatusStop47();
	afx_msg void OnBnClickedButtonStatusStop48();
	afx_msg void OnBnClickedStatusCheck1();
	afx_msg void OnBnClickedStatusCheck2();
	afx_msg void OnBnClickedStatusCheck3();
	afx_msg void OnBnClickedStatusCheck4();
	afx_msg void OnBnClickedStatusCheck5();
	afx_msg void OnBnClickedStatusCheck6();
	afx_msg void OnBnClickedStatusCheck7();
	afx_msg void OnBnClickedStatusCheck8();
	afx_msg void OnBnClickedStatusCheck9();
	afx_msg void OnBnClickedStatusCheck10();
	afx_msg void OnBnClickedStatusCheck11();
	afx_msg void OnBnClickedStatusCheck12();
	afx_msg void OnBnClickedStatusCheck13();
	afx_msg void OnBnClickedStatusCheck14();
	afx_msg void OnBnClickedStatusCheck15();
	afx_msg void OnBnClickedStatusCheck16();
	afx_msg void OnBnClickedStatusCheck17();
	afx_msg void OnBnClickedStatusCheck18();
	afx_msg void OnBnClickedStatusCheck19();
	afx_msg void OnBnClickedStatusCheck20();
	afx_msg void OnBnClickedStatusCheck21();
	afx_msg void OnBnClickedStatusCheck22();
	afx_msg void OnBnClickedStatusCheck23();
	afx_msg void OnBnClickedStatusCheck24();
	afx_msg void OnBnClickedStatusCheck25();
	afx_msg void OnBnClickedStatusCheck26();
	afx_msg void OnBnClickedStatusCheck27();
	afx_msg void OnBnClickedStatusCheck28();
	afx_msg void OnBnClickedStatusCheck29();
	afx_msg void OnBnClickedStatusCheck30();
	afx_msg void OnBnClickedStatusCheck31();
	afx_msg void OnBnClickedStatusCheck32();
	afx_msg void OnBnClickedStatusCheck33();
	afx_msg void OnBnClickedStatusCheck34();
	afx_msg void OnBnClickedStatusCheck35();
	afx_msg void OnBnClickedStatusCheck36();
	afx_msg void OnBnClickedStatusCheck37();
	afx_msg void OnBnClickedStatusCheck38();
	afx_msg void OnBnClickedStatusCheck39();
	afx_msg void OnBnClickedStatusCheck40();
	afx_msg void OnBnClickedStatusCheck41();
	afx_msg void OnBnClickedStatusCheck42();
	afx_msg void OnBnClickedStatusCheck43();
	afx_msg void OnBnClickedStatusCheck44();
	afx_msg void OnBnClickedStatusCheck45();
	afx_msg void OnBnClickedStatusCheck46();
	afx_msg void OnBnClickedStatusCheck47();
	afx_msg void OnBnClickedStatusCheck48();
	afx_msg void OnBnClickedManualStatusCheck1();
	afx_msg void OnBnClickedManualStatusCheck2();
	afx_msg void OnBnClickedManualStatusCheck3();
	afx_msg void OnBnClickedManualStatusCheck4();
	afx_msg void OnBnClickedManualStatusCheck5();
	afx_msg void OnBnClickedManualStatusCheck6();
	afx_msg void OnBnClickedManualStatusCheck7();
	afx_msg void OnBnClickedManualStatusCheck8();
	afx_msg void OnBnClickedManualStatusCheck9();
	afx_msg void OnBnClickedManualStatusCheck10();
	afx_msg void OnBnClickedManualStatusCheck11();
	afx_msg void OnBnClickedManualStatusCheck12();
	afx_msg void OnBnClickedManualStatusCheck13();
	afx_msg void OnBnClickedManualStatusCheck14();
	afx_msg void OnBnClickedManualStatusCheck15();
	afx_msg void OnBnClickedManualStatusCheck16();
	afx_msg void OnBnClickedManualStatusCheck17();
	afx_msg void OnBnClickedManualStatusCheck18();
	afx_msg void OnBnClickedManualStatusCheck19();
	afx_msg void OnBnClickedManualStatusCheck20();
	afx_msg void OnBnClickedManualStatusCheck21();
	afx_msg void OnBnClickedManualStatusCheck22();
	afx_msg void OnBnClickedManualStatusCheck23();
	afx_msg void OnBnClickedManualStatusCheck24();
	afx_msg void OnBnClickedManualStatusCheck25();
	afx_msg void OnBnClickedManualStatusCheck26();
	afx_msg void OnBnClickedManualStatusCheck27();
	afx_msg void OnBnClickedManualStatusCheck28();
	afx_msg void OnBnClickedManualStatusCheck29();
	afx_msg void OnBnClickedManualStatusCheck30();
	afx_msg void OnBnClickedManualStatusCheck31();
	afx_msg void OnBnClickedManualStatusCheck32();
	afx_msg void OnBnClickedManualStatusCheck33();
	afx_msg void OnBnClickedManualStatusCheck34();
	afx_msg void OnBnClickedManualStatusCheck35();
	afx_msg void OnBnClickedManualStatusCheck36();
	afx_msg void OnBnClickedManualStatusCheck37();
	afx_msg void OnBnClickedManualStatusCheck38();
	afx_msg void OnBnClickedManualStatusCheck39();
	afx_msg void OnBnClickedManualStatusCheck40();
	afx_msg void OnBnClickedManualStatusCheck41();
	afx_msg void OnBnClickedManualStatusCheck42();
	afx_msg void OnBnClickedManualStatusCheck43();
	afx_msg void OnBnClickedManualStatusCheck44();
	afx_msg void OnBnClickedManualStatusCheck45();
	afx_msg void OnBnClickedManualStatusCheck46();
	afx_msg void OnBnClickedManualStatusCheck47();
	afx_msg void OnBnClickedManualStatusCheck48();
	afx_msg void OnBnClickedEmeStatusCheck1();
	afx_msg void OnBnClickedEmeStatusCheck2();
	afx_msg void OnBnClickedEmeStatusCheck3();
	afx_msg void OnBnClickedEmeStatusCheck4();
	afx_msg void OnBnClickedEmeStatusCheck5();
	afx_msg void OnBnClickedEmeStatusCheck6();
	afx_msg void OnBnClickedEmeStatusCheck7();
	afx_msg void OnBnClickedEmeStatusCheck8();
	afx_msg void OnBnClickedEmeStatusCheck9();
	afx_msg void OnBnClickedEmeStatusCheck10();
	afx_msg void OnBnClickedEmeStatusCheck11();
	afx_msg void OnBnClickedEmeStatusCheck12();
	afx_msg void OnBnClickedEmeStatusCheck13();
	afx_msg void OnBnClickedEmeStatusCheck14();
	afx_msg void OnBnClickedEmeStatusCheck15();
	afx_msg void OnBnClickedEmeStatusCheck16();
	afx_msg void OnBnClickedEmeStatusCheck17();
	afx_msg void OnBnClickedEmeStatusCheck18();
	afx_msg void OnBnClickedEmeStatusCheck19();
	afx_msg void OnBnClickedEmeStatusCheck20();
	afx_msg void OnBnClickedEmeStatusCheck21();
	afx_msg void OnBnClickedEmeStatusCheck22();
	afx_msg void OnBnClickedEmeStatusCheck23();
	afx_msg void OnBnClickedEmeStatusCheck24();
	afx_msg void OnBnClickedEmeStatusCheck25();
	afx_msg void OnBnClickedEmeStatusCheck26();
	afx_msg void OnBnClickedEmeStatusCheck27();
	afx_msg void OnBnClickedEmeStatusCheck28();
	afx_msg void OnBnClickedEmeStatusCheck29();
	afx_msg void OnBnClickedEmeStatusCheck30();
	afx_msg void OnBnClickedEmeStatusCheck31();
	afx_msg void OnBnClickedEmeStatusCheck32();
	afx_msg void OnBnClickedEmeStatusCheck33();
	afx_msg void OnBnClickedEmeStatusCheck34();
	afx_msg void OnBnClickedEmeStatusCheck35();
	afx_msg void OnBnClickedEmeStatusCheck36();
	afx_msg void OnBnClickedEmeStatusCheck37();
	afx_msg void OnBnClickedEmeStatusCheck38();
	afx_msg void OnBnClickedEmeStatusCheck39();
	afx_msg void OnBnClickedEmeStatusCheck40();
	afx_msg void OnBnClickedEmeStatusCheck41();
	afx_msg void OnBnClickedEmeStatusCheck42();
	afx_msg void OnBnClickedEmeStatusCheck43();
	afx_msg void OnBnClickedEmeStatusCheck44();
	afx_msg void OnBnClickedEmeStatusCheck45();
	afx_msg void OnBnClickedEmeStatusCheck46();
	afx_msg void OnBnClickedEmeStatusCheck47();
	afx_msg void OnBnClickedEmeStatusCheck48();
	afx_msg void OnBnClickedReset1();
	afx_msg void OnBnClickedReset2();
	afx_msg void OnBnClickedReset3();
	afx_msg void OnBnClickedReset4();
	afx_msg void OnBnClickedReset5();
	afx_msg void OnBnClickedReset6();
	afx_msg void OnBnClickedReset7();
	afx_msg void OnBnClickedReset8();
	afx_msg void OnBnClickedReset9();
	afx_msg void OnBnClickedReset10();
	afx_msg void OnBnClickedReset11();
	afx_msg void OnBnClickedReset12();
	afx_msg void OnBnClickedReset13();
	afx_msg void OnBnClickedReset14();
	afx_msg void OnBnClickedReset15();
	afx_msg void OnBnClickedReset16();
	afx_msg void OnBnClickedReset17();
	afx_msg void OnBnClickedReset18();
	afx_msg void OnBnClickedReset19();
	afx_msg void OnBnClickedReset20();
	afx_msg void OnBnClickedReset21();
	afx_msg void OnBnClickedReset22();
	afx_msg void OnBnClickedReset23();
	afx_msg void OnBnClickedReset24();
	afx_msg void OnBnClickedReset25();
	afx_msg void OnBnClickedReset26();
	afx_msg void OnBnClickedReset27();
	afx_msg void OnBnClickedReset28();
	afx_msg void OnBnClickedReset29();
	afx_msg void OnBnClickedReset30();
	afx_msg void OnBnClickedReset31();
	afx_msg void OnBnClickedReset32();
	afx_msg void OnBnClickedReset33();
	afx_msg void OnBnClickedReset34();
	afx_msg void OnBnClickedReset35();
	afx_msg void OnBnClickedReset36();
	afx_msg void OnBnClickedReset37();
	afx_msg void OnBnClickedReset38();
	afx_msg void OnBnClickedReset39();
	afx_msg void OnBnClickedReset40();
	afx_msg void OnBnClickedReset41();
	afx_msg void OnBnClickedReset42();
	afx_msg void OnBnClickedReset43();
	afx_msg void OnBnClickedReset44();
	afx_msg void OnBnClickedReset45();
	afx_msg void OnBnClickedReset46();
	afx_msg void OnBnClickedReset47();
	afx_msg void OnBnClickedReset48();
};
